**MTA 3**

In [2]:
import pandas as pd
import seaborn as sns

df = pd.read_csv("Fair Die.csv")
df

    D1  D2  D3  D4  D5  D6  D7  D8  D9  D10
0    3   6   5   5   2   2   3   5   4    2
1    2   5   3   2   2   4   3   4   6    4
2    3   4   4   1   2   2   1   6   4    5
3    4   5   3   6   2   5   3   6   1    5
4    5   2   1   2   4   3   2   6   2    3
5    2   1   1   6   5   4   1   3   1    4
6    4   2   1   2   5   1   2   1   5    3
7    3   2   5   1   2   4   2   4   5    1
8    3   6   5   5   5   2   3   4   5    1
9    5   3   3   3   3   3   6   6   1    6
10   4   2   5   2   6   4   4   3   4    2
11   2   6   4   6   3   2   2   2   6    3
12   4   6   5   2   3   1   2   4   1    6
13   5   5   3   2   1   6   5   3   4    2
14   3   6   3   2   1   6   3   4   3    1
15   3   2   6   2   5   4   6   6   6    5
16   2   2   3   5   2   4   2   2   3    3
17   3   1   3   2   5   4   5   5   4    5
18   4   6   3   4   4   6   2   6   3    5
19   3   1   4   3   4   5   5   3   6    5
20   3   1   1   4   4   1   1   6   4    6
21   5   6   5   2   6   6   1   2   4    1
22   2   5   2   6   2   4   3   5   1    5
23   3   1   4   5   3   1   1   6   6    5
24   5   3   3   2   3   5   2   6   5    1
25   2   3   4   3   6   4   4   5   4    3
26   2   6   2   5   5   4   4   5   2    3
27   5   5   1   2   4   2   1   4   5    5
28   2   3   6   3   5   5   1   1   4    1
29   2   6   5   6   1   1   4   5   3    4